### ISSUE TITLE
Transfers' object has no attribute 'ban_user'

### ISSUE THREAD

**Issue by dpmccabe** [j4n777/leechdetector_autoban#1]
Hi, @z111ck. I realize this repo is kind of old, but I'm wondering if you're still using it with a newer version of Nicotine. It seems the data model might have changed:

```2023-10-04 09:11:32 Plugin leechdetectorautoban failed with error <class 'AttributeError'>: 'Transfers' object has no attribute 'ban_user'.
Trace:   File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/pluginsystem.py", line 712, in trigger_event
  File "/Users/devin/.local/share/nicotine/plugins/leechdetectorautoban/__init__.py", line 133, in user_stats_notification
    self.core.transfers.ban_user(user)
```

Any ideas what it might take to fix this?

**Comment by j4n777** [comment]
Hey! Nice to see someone found this. Yes, I know. After some update it stopped working because they changed the architecture. Didn't push it to the repo though. I don't really maintain stuff on here.

But I pushed it now, because I also want to use it again. Have fun! :)
